EasyWedding/Models/Gift.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EasyWedding.Models
{
    public class Gift
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public List<GiftItem> Gifts { get; set; }
    }
}

EasyWedding/Models/GiftItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EasyWedding.Models
{
    public class GiftItem
    {
        public int Id { get; set; }
        public int SelectedQuantity { get; set; }
        public decimal SelectedPrice { get; set; }
        public ShopItem Item { get; set; }
        public Gift Gift { get; set; }
    }
}

EasyWedding/Models/ShopItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EasyWedding.Models
{
    public class ShopItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public string Category { get; set; }
        public string PicturePath { get; set; }
    }
}

EasyWedding/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyWedding.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EasyWedding/Controllers/ShopItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EasyWedding.Models;

namespace EasyWedding.Controllers
{
    public class ShopItemController : Controller
    {
        // GET: Store
        public ActionResult Index(int? pageIndex, string sortBy, string filteredCategory)
        {
            var shopItems = GetAllShopItems();
            return View(shopItems);
        }

        [Route("ShopItem/Details/{id}")]
        public ActionResult Show(int id)
        {
            ShopItem shopItem = GetAllShopItems().SingleOrDefault(item => item.Id == id);

            if (shopItem == null)
                return HttpNotFound();

            return View(shopItem);
        }
        
        private IEnumerable<ShopItem> GetAllShopItems()
        {
            return new List<ShopItem>()
            {
                new ShopItem(){ Id = 1, Name = "Item 1" },
                new ShopItem(){ Id = 2, Name = "Item 2" }
            };
        }
    }
}

EasyWedding/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EasyWedding/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EasyWedding/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

EasyWedding/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-defaut navbar-fixed-top">
        <div class="container">
            @*<div class="navbar-header">
                <button type="button" class="navbar-toggle collapse" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Easy Wedding", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>*@
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Loja de Presentes", "Index", "ShopItem")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Easy Wedding, by Leonardo Valverde</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EasyWedding/Views/ShopItem/Index.cshtml
@model IEnumerable<EasyWedding.Models.ShopItem>
@{
    ViewBag.Title = "Loja de Presentes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Loja de Presentes</h2>

@if(!Model.Any())
{
    <text>Não há itens disponíveis no momento.</text>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td>Itens</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var shopItem in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(shopItem.Name, "Show", "ShopItem", new { id = shopItem.Id }, null)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

EasyWedding/Views/ShopItem/Show.cshtml
@model EasyWedding.Models.ShopItem
@{
    ViewBag.Title = "Lista de Presentes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Show</h2>

Name: <text>@Model.Name</text><br />
Description: <text>@Model.Description</text><br />
Quantity Left: <text>@Model.Quantity</text><br />
Unit Price: <text>@Model.UnitPrice</text><br />